openapi: 3.0.0
info:
  title: Product Management API
  version: 1.0.0
  description: API for managing products.
servers:
  - url: http://localhost:8080/api
    description: Local development server
paths:
  /products:
    post:
      operationId: createProduct
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      operationId: getAllProducts
      summary: Find all products
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 25
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      operationId: deactivateProduct
      summary: Deactivate product by id
      parameters:
        - name: id
          in: query
          required: true
          description: The name of the product to deactivate
          schema:
            type: integer
      responses:
        '200':
          description: Deactivate product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /products/{id}:
    get:
      operationId: getProductById
      summary: Find a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
        - currency
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
        currency:
          type: string
        discount:
          type: number
          format: float
        active:
          type: boolean

    ErrorResponse:
      type: object
      required:
        - message
        - details
        - resourceGuid
      properties:
        message:
          type: string
        details:
          type: array
          items:
            type: string
        resourceGuid:
          type: string