###

//1
# curl -X GET https://timeapi.io/api/v1/time/current/unix
GET https://timeapi.io/api/v1/time/current/unix

###

//2
## curl https://timeapi.io/api/v1/time/current/zone?timezone=Europe%2FSamara -H 'accept: */*'

//3
GET https://timeapi.io/api/v1/time/current/ip?ipAddress=46.0.197.26


//4
###
@date = 2026-02-10

GET https://timeapi.io/api/conversion/dayoftheweek/{{date}}

//5
###

POST https://timeapi.io/api/conversion/translate/
Content-Type: application/json

{
  "languageCode" : "ru",
  "dateTime": "2024-05-20 15:30:00",
  "timeZone": "Europe/Moscow"
}





